apiVersion: v1
kind: Pod
metadata:
  name: clamav-updates
  labels:
    clamav: updates
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: cvdupdate
    image: tilleyc/cvdupdate:latest
    volumeMounts:
    - name: shared-data
      mountPath: /var/www/html
    ports:
    - containerPort: 80
