apiVersion: v1
kind: Service
metadata:
  name: clamav-updates-http
spec:
  type: NodePort
  selector:
    clamav: updates
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
