apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-updates
  labels:
    clamav: updates
spec:
  selector:
    matchLabels:
      clamav: updates
  replicas: 2
  template:
    metadata:
      labels:
        clamav: updates
    spec:
      volumes:
      - name: clamav-update-shared
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: clamav-update-shared
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      - name: cvdupdate
        image: tilleyc/cvdupdate:latest
        volumeMounts:
        - name: clamav-update-shared
          mountPath: /var/www/html
